---
- hosts: test-server
  become: true
  remote_user: jenkins
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
  - name: update apt
    command: sudo apt-get update

  - name: install docker
    command: sudo apt install -y docker.io

  - name: start docker service
    command: sudo systemctl start docker

  - name: deploy insureme application
    command: sudo docker run -itd -p 8081:8081 --name insure-me mrajasekhar13/insure-me:1.0
